### ISSUE TITLE
🐛 responsive not work

### ISSUE THREAD

**Issue by boytur** [bsospace/BSOSpace-Blog-Frontend#15]
URL https://demo.bsospace.com/posts/how-to-build-a-rest-api-with-express.js-typescript-mysql

![image](https://github.com/user-attachments/assets/faf26f6c-be6b-4464-b9cb-e3d757804b74)

**Comment by ohmjess** [comment]
Fixed in
(https://github.com/BSO-Space/BSOSpace-Blog-Frontend/commit/84a9b512bdd0d0338771298f3358010f948e3df1)
