### ISSUE TITLE
🐛 Card Alignment Issue: Table of Contents Misaligned with Content

### ISSUE THREAD

**Issue by LordEaster** [bsospace/BSOSpace-Blog-Frontend#18]
![image](https://github.com/user-attachments/assets/689ce761-579d-4e61-b019-2f6fe25e09e5)

The Table of Contents (TOC) card is not aligned properly with the main content area. The TOC card appears offset, causing a visual inconsistency and reducing the UI’s cohesiveness.

**Steps to Reproduce:**
1. 	Navigate to the page containing the TOC card and main content.
2. 	Observe that the TOC card is not aligned with the main content area.

**Expected Behavior:**
The TOC card should align horizontally with the main content area so that both elements appear visually balanced on the page.

**Actual Behavior:**
The TOC card is either slightly lower than the main content area, causing a noticeable misalignment.

![CleanShot 2567-10-26 at 8  16 41](https://github.com/user-attachments/assets/c95c2f9a-5685-4977-8d61-ef9576234733)

**Comment by boytur** [comment]
Fixed in
https://github.com/BSO-Space/BSOSpace-Blog-Frontend/commit/df2068a1606a512801c0867ab6a32a1482de37ef
