### ISSUE TITLE
🌟 Responsive Padding Adjustment: Remove Left and Right Padding on Mobile Screen

### ISSUE THREAD

**Issue by LordEaster** [bsospace/BSOSpace-Blog-Frontend#23]
![image](https://github.com/user-attachments/assets/2d57323a-5128-4788-b7f7-04cb1210080c)

On mobile screens, the content currently has left and right padding, which reduces the usable screen width and may not be necessary. Removing or reducing this padding on mobile could improve the reading experience by allowing more content to fit horizontally. However, on PC screens, the padding should remain to maintain visual structure and readability.

**Feature Requirements:**
1. 	Mobile Screen: Remove or reduce the left and right padding to allow content to utilize the full width of the screen.
2. 	PC Screen: Maintain the current padding for better readability and a visually structured layout.

**Expected Outcome:**
Content on mobile screens should appear edge-to-edge (or with minimal padding), while maintaining the current padding on PC screens to ensure readability and structure.

**Comment by boytur** [comment]
Fixed in 

https://github.com/BSO-Space/BSOSpace-Blog-Frontend/commit/dcf21a2cf1f44d8f87b3d28153a4033409b066ee
