### ISSUE TITLE
🐛 Font Consistency Issue: Table of Contents Header Font Not Matching Rest of Website

### ISSUE THREAD

**Issue by LordEaster** [bsospace/BSOSpace-Blog-Frontend#24]
![CleanShot 2567-10-26 at 8  49 16](https://github.com/user-attachments/assets/116e89d8-88d1-43a0-b8f9-ed0dde9177ed)

On mobile screens, the font used for the “สารบัญ” (Table of Contents) header does not match the font used in the rest of the website’s content. This inconsistency creates a visual discrepancy that affects the cohesive look and feel of the website on mobile devices.

**Steps to Reproduce:**
1. 	Open the website on a mobile device.
2. 	Navigate to any page with the “สารบัญ” (Table of Contents) header.
3. 	Observe that the font style or size differs from the rest of the website’s content on mobile.

**Expected Behavior:**
The “สารบัญ” header on mobile should use the same font style and size as the other headings and content on the website to ensure a consistent appearance.

**Actual Behavior:**
The font of the “สารบัญ” header is visually different on mobile, leading to an inconsistent design.

**Comment by boytur** [comment]
Fixed in 
https://github.com/BSO-Space/BSOSpace-Blog-Frontend/commit/856c9ee6bed373abf357406abc90b1454d602bd0
